### ISSUE TITLE
native-mux feature can't compile anymore

### ISSUE THREAD

**Issue by Fuuzetsu** [openssh-rust/openssh#98]
Seems it depends on openssh-mux-client which depends on tokio-io-utility ^0.6.4 which has been yanked: https://crates.io/crates/tokio-io-utility/versions

A simple setup like this:
```toml
[dependencies]
openssh = { version= "0.9", default_features = false, features = ["native-mux"] }
tokio = { version = "1", default_features = false, features = ["rt-multi-thread"] }
futures = { version = "0.3", default_features = false }
```

Shows the issue:
```console
[nix-develop]$ rm Cargo.lock 
[nix-develop]$ cargo check
    Updating crates.io index
error: failed to select a version for the requirement `tokio-io-utility = "^0.6.4"`
candidate versions found which didn't match: 0.7.1
location searched: crates.io index
required by package `openssh-mux-client v0.15.0`
    ... which satisfies dependency `openssh-mux-client = "^0.15.0"` of package `openssh v0.9.0`
    ... which satisfies dependency `openssh = "^0.9"` of package `start-engine v0.1.0 (/home/shana/programming/start-engine)`
```
